---
title: "The Effect of COVID-19 on Utah Traffic Volumes"
author:
  - name: Matthew Davis
    email: mabosdavis@gmail.com
    affiliation: Brigham Young University
    footnote: 1
  - name: Gregory Macfarlane
    email: gregmacfarlane@byu.edu
    affiliation: Brigham Young University
    footnote: 2
address:
  - code: Brigham Young University
    address: Civil and Environmental Engineering Department, 430 Engineering Building, Provo, Utah 84602
footnote:
  - code: 1
    text: "Corresponding Author"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "Journal"
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
abstract: |
  We report on the results of an experiment to evaluate the effect of the COVID-19 pandemic on traffic volumes in Orem and Cottonwood Heights, Utah. Linear regression models show that COVID-19 resulted in an 11% reduction of vehicles per hour on average. Individual signals, month and day of week were controlled for, but signal detector error resulted in a limited number of signals with usable data available for analysis. While only seven signals were used, this methodology in encouraging for future use with more data.
description: "An analysis of the effect of COVID-19 on traffic volumes in Utah and Salt Lake Counties"
layout: "3p, authoryear"
keywords:
  - COVID-19,
  - Traffic volumes,
  - ATSPM
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage[utf8]{inputenc}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

# Question {#intro}

Since December 2019, the COVID-19 pandemic has affected life around the world in an unprecedented manner. Mask mandates, social distancing, and stay-at-home orders have changed the way society lives, works, and interacts. With these safety precautions have come less interaction, traveling, and driving on roads and highways. Recent research has confirmed that the COVID-19 pandemic has led to a decrease in traffic volumes across the United States and the world.

Although this is a recent event, the topic has already been researched in many states and countries [@Lee2020; @Lee2021; @Muley2021], but has not been specifically looked at for Utah and Salt Lake Counties in Utah, USA. These counties also contain signal specific traffic volume detectors, which provide a detailed insight into the variation of the effect of COVID-19 on traffic volumes in different locations. The research question therefore is:

  - What was the effect of COVID-19 on traffic volumes in Utah and Salt Lake Counties?
